spring.application.name=boveda-digital-api

spring.datasource.url=jdbc:postgresql://db.nigopnvuhetyxgemihqb.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=bovDigCripto
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
