spring.application.name=boveda-digital-api

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.nigopnvuhetyxgemihqb&password=bovDigCripto
spring.datasource.username=postgres
spring.datasource.password=bovDigCripto
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
